### ISSUE TITLE
I2C Write 0xFF to 8 bit I/O expander

### ISSUE THREAD

**Issue by ianccole** [vpaeder/pymcp2221#4]
So, I failed to write bytes([0xff]) to I2C because i2c_write_data() is expecting a string that it can utf8 encode.

If I comment out the .encode("utf8") (Line 1116) it works.

I think writing strings to I2C devices is not very useful

**Comment by vpaeder** [comment]
ok makes sense, now i2c_write_data takes bytearray instead

**Comment by ianccole** [comment]
Thanks for the quick fix. I'll pull that in.
